### ISSUE TITLE
Selection order does not work, always lists chronologically when exporting

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#24]
Users have the ability to export text selections in a variety of options, including in Chronological order and Selection order. Currently, all exports list selections in chronological order despite choosing Selection order. 

Note: This was tested via Plain text and JSON options

1) Open autoEdit 2 app
2) Add file to have access to transcript
3) Open transcript show page
4) Click Export to view options
5) Export via plain text using selection order
6) Open exported file
7) Observe selections listed in chronological order

<img width="606" alt="screenshot 2016-12-12 15 17 29" src="https://cloud.githubusercontent.com/assets/5640831/21115311/c000b9ea-c07e-11e6-93b9-bd07e77df41e.png">

**Comment by pietrop** [comment]
To check if this issue is only for json or for exporting EDL in general.  tried some exports for transcription `Recodes Peter Kafka interviews Turner CEO John Martin Wednesday Nov. 30 7pm ET.mp3` selected first starting at `00:01:32:13`

>because even waking up on election day I would bet that Hillary would want and I actually thought Hillary were won by a considerable margin that was conventional wisdom 

then second starting at  `00:00:05:17`

>the pepper it up there at the end thanks for coming %HESITATION thanks Rick talked late August early September you show me your tattoos I'm hoping that you'll be doing that at some point maybe as a 

When looking at the EDL text selection and EDL json files noticed that they are the same. Both appear in chronological order.

![screen shot 2016-12-13 at 14 28 17](https://cloud.githubusercontent.com/assets/4661975/21155513/6c99cf90-c140-11e6-8023-48709faa990e.png)

![screen shot 2016-12-13 at 14 33 48](https://cloud.githubusercontent.com/assets/4661975/21155716/3a5634f0-c141-11e6-9f07-392f88656ea8.png)

**Comment by pietrop** [comment]
Closing this coz in version `1.0.6` removing selection order export option for transcriptions as adding paperediting feature, which is a better way to the same thing.
