### ISSUE TITLE
EDL file verification (Chronological order)

### ISSUE THREAD

**Issue by jhdouglas** [OpenNewsLabs/autoEdit_2#25]
EDL - Chronological order
Below are the details and files needed for EDL testing via video editing software.

**Video:** First_Town_Hall_For_Transcription.mp4 -- one of the test files you sent QA

**Selected text:** [TC plain text EDL chron Town_Hall Video_EDL_13_12_2016_14-44-36.txt](https://github.com/OpenNewsLabs/autoEdit_2/files/649947/TC.plain.text.EDL.chron.Town_Hall.Video_EDL_13_12_2016_14-44-36.txt)
<img width="731" alt="screenshot 2016-12-13 14 45 32" src="https://cloud.githubusercontent.com/assets/5640831/21156188/ddf5fc16-c142-11e6-90e6-2752fa4dbc04.png">
**EDL file:** [EDL (Chron) Town_Hall Video_chronological_13_12_2016_14-31-31.edl.zip](https://github.com/OpenNewsLabs/autoEdit_2/files/649929/EDL.Chron.Town_Hall.Video_chronological_13_12_2016_14-31-31.edl.zip)

**Comment by pietrop** [comment]
Using following settings when reconnecting EDL file in premiere

![screen shot 2016-12-13 at 15 17 25](https://cloud.githubusercontent.com/assets/4661975/21157518/980da9b0-c147-11e6-9999-fe7c28e4bc03.png)

![screen shot 2016-12-13 at 15 17 31](https://cloud.githubusercontent.com/assets/4661975/21157526/9dd8069c-c147-11e6-9b4d-8ac61dddaa8a.png)

verified that it drifts of out of sync.

Expected 

>[00:00:08:14	00:00:15:22	Unnamed Speaker]
not your traditional town hall I am the only person up here you all are the participants in this town hall and we're going have a 
>
>[00:06:31:16	00:06:46:14	Unnamed Speaker]
we're going to just eventually see it trickle down and I'm not sure that that's necessarily true when we talk about the healthcare space in the six percent of Medicaid beneficiaries that utilize long term care long term services and 
>
>[00:07:57:14	00:08:06:09	Unnamed Speaker]
I think that so much of our preoccupation when we think about healthcare or public health is focused on how can we expand the frontier of what's possible 
>
>[00:09:47:00	00:09:57:11	Unnamed Speaker]
you still have over a hundred thousand central line infections each year even though we know exactly how to get to zero so I wrote a long story kind of exploring that question of why it is 
>
>[00:28:04:09	00:28:11:19	Unnamed Speaker]
food and but seriously when you think about it right so my daughter because of affluence right she doesn't have to be on subsidized or free 
>
>[00:31:26:06	00:31:45:13	Unnamed Speaker]
technologies having kind of the same positive impact is having some of the other sectors so to me when I when I hear all the ideas I know as herb said we shouldn't be constrained by what's possible in the world of politics but I do think one of the questions we have to tackle is how can we make our politics better to make a lot of the changes that were sitting here talking about 
>
>[00:37:05:08	00:37:25:18	Unnamed Speaker]
know what is being achieved so alright well it's unfortunate Arab time but that was an awesome thank you guys for being such good participants I've not moderated anything like this before you do there's other people up here with me but you all have been amazing co panelists or whatever we all are here I'm sorry take about a half hour break we've a few more 


This is what I get instead. word in bold are word that should not be in the selection

>[00:00:08:14	00:00:15:22	Unnamed Speaker]
not your traditional town hall I am the only person up here you all are the participants in this town hall and we're going have a **discussion**
>
>[00:06:31:16	00:06:46:14	Unnamed Speaker]
we're going to just eventually see it trickle down and I'm not sure that that's necessarily true when we talk about the healthcare space in the six percent of Medicaid beneficiaries that utilize long term care long term services and **support**

>[00:07:57:14	00:08:06:09	Unnamed Speaker]
~I think that~ so much of our preoccupation when we think about healthcare or public health is focused on how can we expand the frontier of what's possible **right**

>[00:09:47:00	00:09:57:11	Unnamed Speaker]
~you still~ have over a hundred thousand central line infections each year even though we know exactly how to get to zero so I wrote a long story kind of exploring that question of why it is  **this thing**

>[00:28:04:09	00:28:11:19	Unnamed Speaker]
~ food and but seriously~ when you think about it right so my daughter because of affluence right she doesn't have to be on subsidized or free **lunch but where I work**

>[00:31:26:06	00:31:45:13	Unnamed Speaker]
~technologies having kind of the same~ positive impact is having some of the other sectors so to me when I when I hear all the ideas I know as herb said we shouldn't be constrained by what's possible in the world of politics but I do think one of the questions we have to tackle is how can we make our politics better to make a lot of the changes that were  sitting here talking about **possible, I think one of the tension***

>[00:37:05:08	00:37:25:18	Unnamed Speaker]
~know what is being achieved so~ alright well it's unfortunate Arab time but that was an awesome thank you guys for being such good participants I've not moderated anything like this before you do there's other people up here with me but you all have been amazing co panelists or whatever we all are here I'm sorry take about a half hour break we've a few more **talks coming up feel free to continue**
```

**Comment by pietrop** [comment]
Tried same test but with `PAL` `25fps` settings in premiere.

![screen shot 2016-12-13 at 15 31 13](https://cloud.githubusercontent.com/assets/4661975/21157950/56016082-c149-11e6-9893-ba6c03d014fa.png)

![screen shot 2016-12-13 at 15 31 19](https://cloud.githubusercontent.com/assets/4661975/21157954/58701f52-c149-11e6-9812-ea215c1ada39.png)

And the EDL sequence matches the selections.

**Comment by pietrop** [comment]
see issue [26](https://github.com/OpenNewsLabs/autoEdit_2/issues/26) for more info on this.

**Comment by pietrop** [comment]
Closing this as it is more about the drifting. see https://github.com/OpenNewsLabs/autoEdit_2/issues/26
