### ISSUE TITLE
Other machine learning software and APIs

### ISSUE THREAD

**Issue by sedubois** [OpenNewsLabs/autoEdit_2#40]
I was just curious why IBM watson was used as the API for this tool? (I'm not considering Gentle which is described as not being so performant.)

Watson works great but I guess it could add quite some value to integrate other APIs as well. For example, [Google's speech API](https://cloud.google.com/speech/) supports 101 languages and offers 1 hour of free transcription per month. There are probably quite a few other APIs available as well, and more are bound to come.

As far as open-source is concerned, I also wondered about alternatives to Gentle? For example Tensorflow open-sourced by Google (AFAIK).

**Comment by pietrop** [comment]
Hey @sedubois 
At the time of the development after extensive research it turned out that Watson as the best option. Now this would need to be revisited. 

However I was working on a [branch to add google STT as an option](https://github.com/OpenNewsLabs/autoEdit_2/tree/google_stt) but the google node SDK is not compatible with electron, and that complicates things considerably, so that's on hold for now. 

Others to consider adding are

- Speechmatics 
- Microsoft Bing Speech API
- Baidu STT 
- etc..

I'd also welcome input on adding more effective open source alternatives such as Tensorflow, I personally haven't got my head around that yet.

Closing this for now, unless you are interested in helping out exploring some of this options further. 

Best

Pietro

**Comment by pietrop** [comment]
https://github.com/pietrop/digital-paper-edit-electron/issues/49
