### ISSUE TITLE
Timecode and EDL

### ISSUE THREAD

**Issue by jsdephillips** [OpenNewsLabs/autoEdit_2#46]
Hello, 

  I am using Auto Edit 2 for a documentary and my intern started the transcription process.  I have noticed that the transcripts are using 'running time' instead of the 'actual time-code' embedded in the clips. When I look at the clip info the time-code for the clip is correct.  Is there a way to have the actual time-code in the transcripts? This will be an issue when trying to link clips created in the EDL with paper edit in your program as the time-codes do not match.

Next,  we made a test EDL with paper edit but when I load it into the AVID Media Composer there are no clips in the timeline. I exported a text version of the same EDL and there are events in the EDL.

Also, is there a way to differentiate different speakers? We have several interviews that are 2 people. But all the interviews have the producer asking the questions.  In any case it would be helpful if we could add the name of the main person speaking when we start a new transcript.

Any suggestions would be welcome.

Than you.

Jacquelyn

**Comment by pietrop** [comment]
Hi Jacquelyn, 
Thanks for reaching out.


###  Transcriptions time-codes preview in autoEdit

autoEdit uses 'running time' instead of the 'actual time-code' only when displaying the transcription to make it easier to keep words and video or audio in sync. [Clicking on the words in the transcription view will take you to that point in the media](https://pietropassarelli.gitbooks.io/autoedit2-user-manual/content/transcribing.html).

As you noticed in `info` it shows you the 'actual time-code' it reads from the original media source, so that it can create an EDL that uses those time-codes, that can re-connect to the original media file.

---
### Opening EDL in video editing softwate
When opening EDL in video editing software. The media is generally offline, you then need to reconnect it to the original source. 

[More details on this process in the user manual](https://pietropassarelli.gitbooks.io/autoedit2-user-manual/content/opening-edl-in-video-editing-software.html), and you'd have to see how that is done in Avid. here is a gif of what looks like in Premiere, I'd expect it be similar principle, but probably different menu system.

![5_edl_in_premiere](https://user-images.githubusercontent.com/4661975/38709152-6169cd9c-3eb1-11e8-85b2-227b36f5f51c.gif)

---

### Speaker diarization  
This is something that is on the roadmap, as both [Watson](https://pietropassarelli.gitbooks.io/autoedit2-user-manual/content/setup-stt-apis/setup-stt-apis-ibm.html) and [Speechmatics](https://pietropassarelli.gitbooks.io/autoedit2-user-manual/content/setup-stt-apis/setup-stt-apis-speechmatics.html) have added support for it. I haven't integrated it yet, because it needed figuring out how do you edit the speakers name and how do you allow users to adjust paragraphs if the recognition fails, in case the recognition is not as good as advertised. 

Nonetheless as of version `1.0.8` (current latest version is[`1.0.9`](https://github.com/OpenNewsLabs/autoEdit_2/releases/tag/1.0.9)) it is possible to change the name of the speaker at the top of the transcription.

- You just click on the `Unnamed Speaker`
- Edit the text
- And it auto saves 

see screenshot below.

![screen shot 2018-04-13 at 00 39 29](https://user-images.githubusercontent.com/4661975/38709472-2b847ee6-3eb3-11e8-9f6a-234b5af97b60.png)

 As I though this might help when using the [paper-editing feature](https://pietropassarelli.gitbooks.io/autoedit2-user-manual/content/paperediting.html).

---

Hope this helps for now, let me know if any of that is not clear, and if you have got any questions.

**Comment by pietrop** [comment]
@jsdephillips I am closing this issue, but if you find you have any problem with the EDL export feel free to comment it here and we can re-open it.

**Comment by jsdephillips** [comment]
Hi Pieto,


We have not been able to get an edl to work but I'm too busy to spend more time on it right now.


I'm looking forward to the PC version.


Thanks


Jacquelyn De Phillips On Mon, Apr 16, 2018 at 6:27pm, Pietro < notifications@github.com [notifications@github.com] > wrote:
Closed #46 [https://github.com/OpenNewsLabs/autoEdit_2/issues/46] .

**Comment by pietrop** [comment]
@jsdephillips any chance you could upload the EDL here? 

I might be able to identify the issue by looking a the file autoEdit generated. 

I might also be able to help if you can provide a bit more details on the workflow you followed. 

For example, what camera did you use? and what file type did you upload into autoEdit? Was that the raw footage from the camcorder or you transcoded it first?

**Comment by pietrop** [comment]
Thanks @jsdephillips, Not a problem, whenever is most convenient for you.
