### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [OpenNewsLabs/autoEdit_2#57]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by pietrop** [comment]
Hi @mansya,
Sounds great and thanks for reaching out, because this is an electron app, that is bundled into a desktop application, the logos and icons are in the [`/build` folder](https://github.com/OpenNewsLabs/autoEdit_2/tree/master/build)

This is the current logo users see when installing the app:

![autoEdit logo](https://raw.githubusercontent.com/OpenNewsLabs/autoEdit_2/master/build/autoedit.png)

But I'd be happy to consider a new and improved logo, suggestions welcome  😄

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ?
![autoedit](https://user-images.githubusercontent.com/33461607/43527707-6bfb6618-95d1-11e8-863c-b2c14d15dec0.png)

**Comment by mansya** [comment]
sorry about the issues that I close. I accidentally clicked on it

**Comment by pietrop** [comment]
Thanks @mansya , I think I want to keep with the button idea tho :)

**Comment by mansya** [comment]
Thanks. i will try some more time

**Comment by pietrop** [comment]
closing this for now, but feel free to re-open if you have any updates.
