### ISSUE TITLE
.srt captions process endlessly (Windows 10)

### ISSUE THREAD

**Issue by sam1am** [OpenNewsLabs/autoEdit_2#95]
Submitting a video file along with an .srt file shows processing endlessly on the Transcriptions page and never completes. 

![image](https://user-images.githubusercontent.com/127555/72855378-81379d80-3c74-11ea-8397-2aba6d4f9800.png)

I'm running WIndows 10 v1909. 
Autoedit 1.0.22

**Comment by pietrop** [comment]
Thanks @sam1am if you click option (`⌥`) + command (`⌘`) + `i` keys and then view the `console` tab, what kind of error message do you see if any (could you share a screenshot here)?

_note, you would only see errors if you haven't re-started or closed the application since the error occurred. When you close and re-open the console re-sets itself, so in that case you might need to reproduce the error again, eg upload another file with captions to re-create the issue. if that make sense._

**Comment by sam1am** [comment]
It looks like maybe your user directory is hard coded somewhere... 

It's trying to call the file 'C:\Users\pietropassarelli\Dropbox\CODE\Vox\TBVE\autoEdit_2\lib\interactive_transcription_generator\transcriber\captions\examples\srtLineJson.json'

![image](https://user-images.githubusercontent.com/127555/73040958-c98fc080-3e18-11ea-976d-7ea09ae56eb1.png)
![image](https://user-images.githubusercontent.com/127555/73040976-dc09fa00-3e18-11ea-94c2-ae0979039d1e.png)

**Comment by pietrop** [comment]
Thanks for flagging this @sam1am  looks like I left that in there from the last troubleshooting, my bad. I just made a new release that should have the fix [1.0.23](https://github.com/OpenNewsLabs/autoEdit_2/releases/tag/1.0.23)

Let me know if you have a chance to try it out

**Comment by sam1am** [comment]
Confirmed fixed (however, the old transcriptions continue to process endlessly and cannot be canceled).

**Comment by pietrop** [comment]
Did you try the Btn “delete pending transcripts”?

That should do the trick (it’s a workaround introduced by @bfasenfest )
